version: "3.3"

services:
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    networks:
      - mysql-phpmyadmin

  # Database
  db:
    image: mysql:5.7
    container_name: Mysqldb
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_DATABASE: phpmyadmin
      MYSQL_USER: rakhafe
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_root_password
      - db_password
    networks:
      - mysql-phpmyadmin

secrets:
   db_password:
     file: db_password.txt
   db_root_password:
     file: db_root_password.txt

networks:
  mysql-phpmyadmin:

volumes:
  db_data: