version: '3.2'
services:
  portainer:
    image: portainer/portainer-ce:2.0.0-alpine
    container_name: portainer
    command: -v "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - 9000:9000
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"  
      - "data_portainer:/data"
    restart: always

volumes:
  data_portainer:  



